"""Build transparent Markdown evidence directly from the two saved runs."""
from pathlib import Path
import json
import math
import re
ROOT=Path(__file__).resolve().parents[1]
ledger=json.loads((ROOT/'experiment_runs.json').read_text())
def read(path): return json.loads((ROOT/path).read_text())
runs={n:{'path':v['run_dir'],'notebook':v['notebook'],'wall':v['wall_seconds']} for n,v in ledger.items()}
for n,r in runs.items():
 for f in ['config','training_summary','inspection','history','language_eval_comparison','tokenization','corpus_manifest','vocabulary_report','temperature_comparison','checkpoint','eval_separation']:
  r[f]=read(f"{r['path']}/{f}.json")
 r['cases']={s:read(f"{r['path']}/language_evals/{s}/eval_results.json") for s in ['untrained','final']}
s=runs['starter']; e=runs['expanded']
def pct(x): return 'N/A' if x is None else f'{100*x:.2f}%'
def cell(x): return str(x).replace('|','\\|').replace('\n',' ')
def metric(m): return f"{m['correct']}/{m['total']} ({pct(m['success_rate_all_cases'])}); {m['scorable']}/{m['total']} ({pct(m['coverage'])}); {pct(m['accuracy_scorable_cases'])}"
def link(r,f,label=None,up=''): return f"[{label or f}]({up}{r['path']}/{f})"
readme=[]
def a(t=''): readme.append(t)
a('# Class 4: two executed custom-LLM experiments')
a('Both fresh nanoGPT runs completed 3,000 updates. The starter scored **20/48 (41.67%)** after training; the expanded corpus scored **24/48 (50.00%)**. The expansion increased test vocabulary coverage, but **none of the 24 extension cases passed after training**. Its four additional correct answers came from the familiar-vocabulary `new_wording` category. The intended grammar/opposites transfer did not succeed on this benchmark. These are model measurements, not an assignment grade.')
a('This repository contains actual executed notebooks, saved trained and untrained weights, all 192 case results, raw samples, and a recorded terminal session. Results below come from this project’s runs; upstream `examples/` and `legacy/` are teaching references and are not evidence for these experiments. Confidence is **high** in the recorded counts and outputs; **moderate** that the observed changes reflect learning narrow corpus patterns; **low** in any claim that adding these examples caused the improvement independently of initialization and split changes. No broad generalization claim is made.')
a('## Evidence entry points')
for n,r in runs.items():
 a(f"- **{n.title()}**: [executed notebook]({r['notebook']}), [complete run folder]({r['path']}/), [results ZIP]({r['path']}.zip). Run ID: `{Path(r['path']).name}`.")
a('- [Detailed learning evidence](docs/learning_evidence.md): complete 64-coordinate before/after vectors, gradients, probabilities, all timeline and temperature samples, and case-by-case score changes.')
a('- [Actual terminal recording](evidence/chat_recording.html), [recording source](evidence/chat.cast), [terminal text](evidence/chat_terminal.txt), and [chat transcript](evidence/chat_transcript.json). Download/open the HTML locally to play it if GitHub shows its source.')
a('- [Prediction recorded before training](docs/pretraining_plan.md), [corpus rationale and provenance](docs/corpus_design.md), [execution ledger](experiment_runs.json), and [original assignment](ASSIGNMENT.md).')
a('## What was chosen and why')
a('**Corpus:** first the supplied synthetic classroom corpus with no added files, then the same classroom generator plus focused **grammar** and **opposites** teaching material. The starter repeats domain associations; the expansion was intended to add subject/verb agreement, tense, and contextual contrasts. The [deterministic generator](scripts/build_extension_corpus.py) created 528 grammar passages and 384 contextual contrast passages, and the executed manifest confirms all **912 unique additions**. They use different roles, situations, and wording from the test stories. They are varied templates, not 912 independent underlying situations.')
a('**Training budget:** 3,000 optimizer steps per fresh model, batch size 32, the suggested course starting budget. One step updates weights from a minibatch; it is not a complete corpus pass. **Learning rate:** 0.001 as the configured peak, with the supplied 100-step warmup and cosine decay. The first effective rate is 0.00001. Excessively large updates could destabilize the loss; very small ones could make too little progress within 3,000 steps. These are assistant-proposed choices recorded before execution, not an invented personal response from the student.')
a('The model has 2 transformer blocks, 4 attention heads, 64-dimensional embeddings, a 48-token context, and seed 42. Training ran locally on CPU; saved hardware is `macOS-26.6.2-arm64-arm-64bit`, Python 3.12.14 and PyTorch 2.14.0. No GPU or external model API supplied the generated replies. The unchanged nanoGPT source is pinned to [Karpathy commit 3adf61e](https://github.com/karpathy/nanoGPT/blob/3adf61e154c3fe3fca428ad6bc3818b27a3b8291/model.py), with its [MIT license](NANOGPT_LICENSE). Whole-word tokenization and teaching/evaluation helpers come from the [course project](https://github.com/pepealonso95/custom-llm).')
a('## Corpus, permissions, and experimental controls')
a('The starter text is generated by the supplied course code. The two added UTF-8 TXT files are original synthetic examples created with Codex assistance for this project; no private records, scraped passages, or third-party source documents were added. They may be shared with this project; commonplace sentences are not claimed as exclusive intellectual property. Source files: [grammar](corpus/expanded/grammar_practice.txt) and [contextual contrasts](corpus/expanded/contextual_contrasts.txt). Source hashes, previews, and passage counts are saved in the manifests. No PDFs were used, so OCR, page extraction, and PDF reading-order checks were not applicable. Both imported files have empty warning lists, and no files were ignored.')
a('| Measurement | Starter | Expanded |\n|---|---:|---:|')
rows=[('Unique passages',s['corpus_manifest']['unique_passages'],e['corpus_manifest']['unique_passages']),('Added unique passages',0,912),('Training / validation passages',f"{s['config']['train_documents']} / {s['config']['validation_documents']}",f"{e['config']['train_documents']} / {e['config']['validation_documents']}"),('Vocabulary including UNK/BOS/EOS',s['config']['vocabulary_size'],e['config']['vocabulary_size']),('Retained ordinary token types',s['vocabulary_report']['retained_types'],e['vocabulary_report']['retained_types']),('Training / held-out token UNK rate','0.00% / 0.00%','0.00% / 0.00%'),('Parameters',f"{s['config']['parameters']:,}",f"{e['config']['parameters']:,}"),('Completed optimizer steps',3000,3000),('Training-loop elapsed seconds',f"{s['training_summary']['elapsed_seconds']:.6f}",f"{e['training_summary']['elapsed_seconds']:.6f}"),('Full notebook wall seconds',f"{s['wall']:.6f}",f"{e['wall']:.6f}"),('Interrupted','No','No')]
for row in rows: a('| '+' | '.join(map(str,row))+' |')
a('Both runs remove 160 generated passages containing reserved test prefixes and remove 1,608 duplicate passages, then use a 90/10 split of unique passages. The vocabulary is built only from the training split (maximum 509 ordinary types plus three special tokens). No token types were omitted in these runs. A zero held-out UNK rate describes the corpus split; it does not mean complete coverage of the separate eval suite.')
a('Within each run, the vocabulary, train/validation split, fixed loss panels, seed and baseline generation settings are unchanged before/after training. Across the two fresh runs, adding passages changes split membership and panels; changing vocabulary changes token IDs, embedding/output dimensions, parameter counts, and random initialization even with seed 42. Thus this is an informative development comparison, not an exact paired causal experiment. The two loss scales also refer to different vocabularies and data, so their absolute values should not rank the models.')
for n,r in runs.items():
 a(f"**{n.title()} audit links:** "+' · '.join(link(r,f) for f in ['config.json','corpus_manifest.json','vocabulary_report.json','split.json','corpus.txt','tokenization.json','training_summary.json','eval_separation.json']))
a('## Before training: prediction; after training: observation')
a('The [pretraining plan](docs/pretraining_plan.md) predicted, with moderate confidence, falling training and held-out panel loss and increasingly corpus-like text. Those predictions were observed within both runs. It also predicted only low-to-moderate confidence of grammar/opposites improvement. That prediction was not supported: coverage expanded by three cases, but the expanded trained model missed all three newly scorable extension cases. One grammar and one opposites case were correct in its random untrained state and became incorrect after training; chance-correct initialization is not evidence of understanding.')
a('The plan suggested that `customer` could become more similar to buyer-related nouns, without predicting their ordering. The full-vector evidence reports the actual nearest neighbors rather than treating a 3D picture as proof of meaning. Successful domain templates and lower loss coexist with malformed text and failed transfer.')
a('## All four complete evaluation result sets')
a('The unchanged suite has 16 starter-pattern cases, 8 familiar-vocabulary new phrasings, and 24 extension challenges. The runner supplies only each prefix to the model, then scores whether the correct next word has uniquely highest probability **among four choices**. It does not append the choices or key to the prompt and does not update weights. Ties receive zero. A case is unscorable if required prompt/choice vocabulary is missing or its context is too long; it remains in the 48-case denominator with zero credit. Scorable accuracy is correct/scorable; coverage is scorable/total. `N/A` means no scorable cases, not zero-percent measured accuracy. The free continuation is separately sampled and is not the scored answer.')
a('| Experiment / stage | Correct / all | All-case success | Scorable | Scorable accuracy | Coverage | Complete evidence |\n|---|---:|---:|---:|---:|---:|---|')
for n,r in runs.items():
 for stage in ['untrained','final']:
  m=r['language_eval_comparison'][stage]['overall'];base=f'language_evals/{stage}/'
  links=' · '.join(link(r,base+f,l) for f,l in [('eval_results.json','JSON'),('eval_results.csv','CSV'),('eval_summary.json','summary'),('eval_cases.json','cases')])
  a(f"| {n.title()} / {stage} | {m['correct']}/{m['total']} | {pct(m['success_rate_all_cases'])} | {m['scorable']} | {pct(m['accuracy_scorable_cases'])} | {pct(m['coverage'])} | {links} |")
a('Every case is retained, including failures and unknown-word cases. The suite SHA-256 recorded in all stages is `1d7c503f34d88260d0ac897bc36b8ba621cccc1950aef47e7121e69b2c1c9e1d`. Each run’s separation record confirms 160 generated passages excluded. The check is normalized contiguous-prefix detection, **not** a semantic-leakage detector. The source generator, eval suite, transcripts and result directories remain separate; the corpus folder is explicitly `corpus/starter` or `corpus/expanded`, never the project root. The public benchmark informed the category choices, so it is a development benchmark, not an untouched test of generalization.')
a('The following tables report **correct/total (all-case success); scorable/total (coverage); scorable accuracy** in each cell.')
for key,title in [('by_group','Group results'),('by_category','Category results')]:
 a(f'### {title}')
 a('| Group or category | Starter untrained | Starter trained | Expanded untrained | Expanded trained |\n|---|---|---|---|---|')
 for k in s['language_eval_comparison']['untrained'][key]:
  a('| '+k+' | '+' | '.join(metric(r['language_eval_comparison'][stage][key][k]) for r in [s,e] for stage in ['untrained','final'])+' |')
a('### What improved and what failed')
a('The trained-to-trained gains are exactly `lang_18`, `lang_19`, `lang_22`, and `lang_23`; no starter-trained correct case became incorrect in the expanded-trained model. All four were already scorable in the starter, so the additional four correct answers are not simply newly counted vocabulary coverage. However, the model initialization and split also changed, so a single pair of runs does not isolate why these four improved. The extension group went from 0/24 to 0/24 after training despite coverage increasing from 0/24 to 3/24. Within the expanded run, extension accuracy actually fell from 2/3 to 0/3 scorable cases.')
a('| Concrete case | Expanded trained outcome | Interpretation |\n|---|---|---|')
for cid,interpret in [('lang_27','All required words were known; the tense pattern failed.'),('lang_28','Contrast vocabulary was present, but transfer to this question form failed.'),('lang_29','Coverage alone did not yield the tested opposite relation.'),('lang_25','Missing prompt vocabulary prevents a valid four-choice score.'),('lang_30','A missing distractor also makes a case unscorable; it is not dropped.')]:
 c=next(x for x in e['cases']['final'] if x['id']==cid)
 unknown=', '.join(c['unknown_prompt_words']+c['unknown_choices']) or 'none'
 a(f"| `{cid}`: `{c['prompt']}`; expected `{c['expected']}` | Choice: `{c['predicted_choice']}`; status `{c['status']}`; unknown words: {unknown}. Continuation: `{cell(c['generated_text'])}` | {interpret} |")
a('A correct choice need not be the free continuation. For starter-trained `lang_03`, the highest-probability offered choice was `payment` (0.257614), but the sampled continuation was `return in detail .`. For expanded-trained `lang_19`, the correct offered choice was `return`, while free generation was `interest .`. Neither result proves that unrestricted generation reliably produces the expected answer.')
a('## Full fixed-panel loss measurements')
a('Each row is the mean cross-entropy over all non-padding next-token targets in the same fixed **20 training passages and 20 validation passages** within that run. These are small panels, not full-corpus measurements. Lower loss means the model assigned more probability to the observed next tokens; it is not an accuracy percentage.')
a('| Experiment | Step | Training loss | Validation loss |\n|---|---:|---:|---:|')
for n,r in runs.items():
 for h in r['history']: a(f"| {n.title()} | {h['step']} | {h['training_loss']!r} | {h['validation_loss']!r} |")
for n,r in runs.items():
 a(f"**{n.title()}:** "+link(r,'training.csv','full CSV')+' · '+link(r,'history.json','raw values'))
 a(f"![{n.title()} fixed-panel losses]({r['path']}/training_curves.svg)")
a('Both held-out panel losses fell along with training loss. This supports learning on closely related synthetic templates; the passage split allows related frames and source files on both sides. It does not establish generalization to new templates, domains or documents. The expanded final sample `last week the musicians low .` is worse than its halfway sample `last week the musicians walked through the park .`, even though panel loss improved. Four saved samples are too few to estimate a general fluency rate.')
a('All four samples at each of steps 0, 1,500 and 3,000 are shown unedited in [learning evidence](docs/learning_evidence.md). Baseline settings are BOS start, temperature 0.8, seed 2026 and at most 32 generated tokens, with EOS stopping. Nothing was omitted because it was garbled. All 12 temperature samples per run are also preserved. At each temperature the generator resets to the same seed and BOS start; because sampled length changes random-number consumption, later samples are matched by generator setup, not guaranteed identical per-token random draws.')
for n,r in runs.items(): a(f"**{n.title()} sample links:** "+' · '.join(link(r,f) for f in ['samples/step_0000.txt','samples/step_1500.txt','samples/step_3000.txt','temperature_comparison.json']))
a('## How the model learned, using actual evidence')
a('A **corpus** is the teaching text. **Tokens** here are lowercase words and punctuation, with BOS/EOS marking boundaries and UNK for missing types. An **ID** is an arbitrary vocabulary index, not a semantic rank. In the starter, `customer` is ID 28; in the expanded run it is ID 62 because the vocabulary changed. Each ID selects a learned **64-number embedding vector**. These lookup vectors combine with position embeddings and pass through the network’s learned attention and feed-forward weights; hidden representations become context-dependent. A coordinate is not a named concept.')
a('The starter’s `customer` coordinate 0 began at **−0.057591915130615234**, had a saved first-step gradient **0.000692586530931294**, and changed to **−0.05760190635919571** after the first update at effective learning rate **0.00001**. After 3,000 updates it was **0.0366341732442379**. The gradient measures local sensitivity of minibatch loss to that weight, not a semantic instruction. The recorded gradient is before global-norm clipping. AdamW uses moving averages of gradients and squared gradients, bias correction, and decoupled weight decay; therefore this change is not simply `−learning_rate × saved_gradient`. The supplied optimizer uses betas (0.9, 0.95), weight decay 0.01 and clipping at global norm 1.0. Full vectors and the expanded update are in [learning evidence](docs/learning_evidence.md).')
a('The neural network contains trainable embedding and linear-transformation weights, nonlinear GELU feed-forward layers, layer normalization, and residual connections. Input and output token-embedding weights are tied. Training predicts each next token from previous tokens. Cross-entropy penalizes assigning low probability to the actual next token. PyTorch backpropagation calculates gradients through the network, and AdamW updates its weights. Repeating this process changed the starter next-token distribution after `the customer`: plausible corpus verbs receive substantial probability after training, while the initial distribution was diffuse. The detailed evidence gives actual probability tables and the complete distribution is saved in `inspection.json`. These are probabilities of next tokens, not confidence that a generated sentence is factually true.')
a('Attention forms learned queries, keys and values, compares queries with earlier keys, normalizes the scores and combines value vectors. The causal mask prohibits looking ahead. For the starter’s trained first layer/head on `[BOS, the, customer]`, the last attention row is **[0.485155, 0.423004, 0.091841]**. The first row is [1, 0, 0] and the second has zero in the future position, making masking visible. This one head’s weights do not fully explain a prediction; other heads, layers and the feed-forward path also contribute.')
a('Generation converts logits to probabilities and samples a token, appends it to context and repeats. Temperature uses `softmax(logits / T)` without changing any learned weights. Lower temperature concentrates mass on likely tokens; higher temperature flattens it. Here 0.3, 0.8 and 1.2 were compared with the same starting token and seed. Some outputs stayed identical: the starter’s first sample is the same at all three settings. In the expanded run, 0.8 produced `last week the musicians low .`; 1.2 produced other corpus-like examples. This small sample is not evidence that higher temperature is generally more grammatical.')
a('## Working chat and exact launch instructions')
a('The supplied [chat.py](chat.py) loads the expanded run’s actual `model.pt` and saved vocabulary, then repeatedly accepts input. Every prompt starts fresh; there is no conversation memory or training during chat. It reports unknown words and truncates long prompts to the most recent context. The interface has a 48-token context and generates up to 24 new tokens at temperature 0.8. `checkpoint.json` is for the embedding viewer, not the full inference model.')
a('From the repository root, use Python 3.12. The lock file reproduces the recorded dependency versions; it was generated on macOS. Use the same Python environment when selecting a VS Code/Jupyter notebook kernel. A full Jupyter GUI is optional: the included nbclient execution script runs notebooks directly.')
a('```sh\npython3.12 -m venv .venv\nsource .venv/bin/activate\npython -m pip install -r requirements-lock.txt\npython -m ipykernel install --prefix .venv --name python3 --display-name "Custom LLM (Python 3.12)"\n```')
a('Open [custom_llm.ipynb](custom_llm.ipynb) or [custom_llm_expanded.ipynb](custom_llm_expanded.ipynb) in VS Code/Jupyter, select that environment, and use Run All. To execute fresh experiments programmatically, the script uses the supplied source notebook and preserves all real cell outputs; it overwrites the executed notebook and updates the ledger while retaining timestamped run folders, so keep a copy of submitted evidence before rerunning:')
a('```sh\npython scripts/execute_experiment.py starter\npython scripts/build_extension_corpus.py --check\npython scripts/build_extension_corpus.py\npython scripts/execute_experiment.py expanded\n```')
a('The two submitted models are already included in their run folders and ZIPs, so training is not required to replay evaluation or chat. Use a new output/transcript name when preserving earlier evidence:')
a('```sh\n'+f"python run_evals.py --model {s['path']}/model_untrained.pt --output results/starter-untrained\npython run_evals.py --model {s['path']}/model.pt --output results/starter-final\npython run_evals.py --model {e['path']}/model_untrained.pt --output results/expanded-untrained\npython run_evals.py --model {e['path']}/model.pt --output results/expanded-final\npython chat.py --model {e['path']}/model.pt --transcript results/new-chat.json\n"+'```')
a('The recorded terminal session used expanded run `20260923T062639_403952Z`, 3,000 completed steps, and model-state hash `759c8b1e9c073f74b820d3c962fa108b5793a5b9c67ee263328e01ee6fe9cbd8`. These were actual inputs and outputs; the assistant scripted the demonstration rather than claiming the student personally typed it.')
a('| Input | Actual model continuation | Unknown words |\n|---|---|---|')
for t in read('evidence/chat_transcript.json')['turns']: a(f"| `{t['prompt']}` | `{cell(t['response'])}` | {', '.join(t['unknown_prompt_words']) or 'None'} |")
a('The quantum prompt demonstrates the limitation: all three words were unknown and the model emitted an unrelated corpus-style continuation. It has no mechanism for explaining quantum teleportation. The cups prompt also fails coherently because `cups` is outside the vocabulary. [Replay the recording](evidence/chat_recording.html) and inspect the [saved transcript](evidence/chat_transcript.json), which records seeds and truncation flags.')
a('![Actual terminal recording replay](evidence/chat_screenshot.png)')
a('The image above is a screenshot of the actual terminal recording replay. [Reproduction and review notes](docs/reproduction_notes.md) explain how the execution and derived artifacts were prepared.')
a('## Limitation, next experiment, and assistance disclosure')
a('The most consequential result is that adding grammar and contrast sentences improved corpus loss and vocabulary coverage without passing the targeted extension tests. The teaching examples may not transfer to the test’s tense and “opposite of” forms. That explanation is a hypothesis, not a proven cause. The corpus also contains five mechanically generated phrases of the form `a artist seems ...`, an article-agreement error found during review. Those mistakes are disclosed and preserved in the executed experiment; silently correcting the source would make it inconsistent with the saved trained weights.')
a('The next experiment should first correct those five article errors and audit agreement/tense in the generated material, then run fresh models while holding data constant across multiple initialization seeds to estimate variability. A separate, newly designed suite of grammatical and contrast tasks should be frozen before further corpus revision, with unseen situations and phrasing. An ablation can then change only one teaching category at a time while keeping an anchored shared evaluation set and reporting vocabulary coverage. Longer training alone cannot supply missing words, and selecting examples to match this public benchmark would not establish unseen generalization.')
a('Codex helped design and generate the extension corpus, execute the notebooks and chat demonstration, inspect saved evidence, audit results, and write this report. The core model and classroom pipeline are attributed above. All numeric results and quoted model outputs are saved artifacts; no student-authored reflection, independent understanding, or portal submission is claimed. The report is intended to be reviewed alongside the notebook so the student can explain what was measured, what failed, and what remains uncertain.')
a('## Actual embedding viewers')
a('Open the [starter viewer](evidence/embeddings_starter.html) or [expanded viewer](evidence/embeddings_expanded.html) locally. Each embeds its actual recorded checkpoint, so no file picker is required. The expanded viewer’s shared 3D PCA projection retains only 22.2% of pooled variance; the displayed neighbor rankings use all 64 dimensions. Its customer neighbors changed from traffic, chair and waiting before training to subscriber, client and shopper afterward. This is evidence about narrow learned distributional contexts, not an independently validated semantic map.')
a('![Expanded customer before training](evidence/embeddings_before.png)\n\n![Expanded customer after training](evidence/embeddings_after.png)')
(ROOT/'README.md').write_text(re.sub(r'(?m)(^\|[^\n]*\|)\n\n(?=\|)', r'\1\n', '\n\n'.join(readme))+'\n')
# Detailed evidence, generated entirely from recorded JSON/text.
out=[]
def b(t=''): out.append(t)
b('# Detailed learning evidence from the two executed runs')
b('This companion exposes actual saved values and all saved generation samples. It is generated by [build_report.py](build_report.py) from the [run ledger](../experiment_runs.json); the README interprets these observations. Values are formatted for readability, while linked JSON preserves their full stored precision. No vectors or replies were invented.')
for n,r in runs.items():
 ins=r['inspection'];tok=r['tokenization']; vocab=tok['vocabulary'];u=ins['first_update']
 b(f'## {n.title()} run: `{Path(r["path"]).name}`')
 b(f"Source: {link(r,'inspection.json',up='../')} and {link(r,'tokenization.json',up='../')}. The word `{ins['token']}` has ID **{ins['token_id']}** and 64 embedding coordinates. IDs are indices, not meaning; they differ across vocabularies.")
 b(f"Actual tokenization example: `{tok['example']}`. With BOS/EOS its IDs are `{tok['ids']}`. The input IDs are `{tok['inputs']}` and next-token targets are `{tok['targets']}`. This one-token shift supplies the supervised signal without a separate human answer label.")
 b('| Coordinate (zero-based) | Before training | After 3,000 steps |\n|---|---:|---:|')
 for i,(x,y) in enumerate(zip(ins['embedding_before'],ins['embedding_after'])): b(f'| {i} | {x:.12g} | {y:.12g} |')
 b(f"**Real first update:** coordinate {u['coordinate']}, before `{u['before']}`, gradient `{u['gradient']}`, effective learning rate `{u['learning_rate']}`, after `{u['after']}`; observed change `{u['after']-u['before']}`. The saved gradient is before norm clipping; the optimizer is AdamW, not plain gradient descent. The eventual full-vector movement reflects all 3,000 updates, not this one step.")
 # nearest neighbors calculated in all 64 dimensions
 initial=r['checkpoint']['initial_embeddings']; final=r['checkpoint']['weights']['wte'];pid=ins['token_id']
 def nn(mat):
  q=mat[pid];qn=math.sqrt(sum(x*x for x in q));ans=[]
  for i,v in enumerate(mat):
   if i==pid or vocab[i].startswith('<'):continue
   co=sum(x*y for x,y in zip(q,v))/(qn*math.sqrt(sum(x*x for x in v)))
   ans.append((co,vocab[i]))
  return sorted(ans,reverse=True)[:3]
 b('Nearest ordinary-token neighbors by cosine similarity in all 64 dimensions (derived from the saved lookup table): before = '+', '.join(f'`{w}` ({v:.6f})' for v,w in nn(initial))+'; after = '+', '.join(f'`{w}` ({v:.6f})' for v,w in nn(final))+'. Similarity reflects these designed contexts and is not a proof of human-like meaning.')
 b(f"### Actual next-token probabilities after `{ins['prefix']}`")
 b('The following union contains the top eight tokens before and after training, with both probabilities shown. This is a readable subset; `inspection.json` retains all probabilities in the `tokenization.json` vocabulary order.')
 ids=set(sorted(range(len(vocab)),key=lambda i:ins['probabilities_before'][i],reverse=True)[:8]+sorted(range(len(vocab)),key=lambda i:ins['probabilities_after'][i],reverse=True)[:8])
 b('| Token | Before | After |\n|---|---:|---:|')
 for i in sorted(ids,key=lambda i:ins['probabilities_after'][i],reverse=True): b(f"| `{vocab[i]}` | {ins['probabilities_before'][i]:.9f} | {ins['probabilities_after'][i]:.9f} |")
 b('First layer/head causal-attention matrix on `[BOS, the, customer]`, rows = query positions and columns = key positions. Future columns are zero; attention includes the current token as well as earlier tokens:\n\n```json\n'+json.dumps(ins['attention_rows'],indent=2)+'\n```')
 b('### All timeline samples, unchanged')
 b('At each checkpoint: BOS start, temperature 0.8, CPU sampling-generator seed 2026, four samples, maximum 32 new tokens, stopping at EOS. Empty output would be shown as `[empty output]`; no examples are selected away.')
 for p in sorted((ROOT/r['path']/'samples').glob('*.txt')):
  b(f"**{p.stem}:** [{p.name}](../{p.relative_to(ROOT)})\n\n```text\n"+p.read_text()+'\n```')
 b('### Full temperature comparison')
 b('The model weights are fixed. Each temperature call resets the seed to 2026 and begins each sample with BOS. Later samples can consume different points in the random stream when earlier generated lengths differ.')
 for temp,samples in r['temperature_comparison'].items(): b(f'**Temperature {temp}:**\n\n```text\n'+'\n'.join(x or '[empty output]' for x in samples)+'\n```')
b('## Every case: four-stage score/status audit')
b('Cell format is `score / status`. `out_of_vocabulary` receives zero in all-case success. Full prompt, four choices, key, probability values, explanation, sample seed and free continuation for every stage are in the linked JSON/CSV sets in the README. The following is a compact way to verify no case disappeared.')
b('| ID | Category | Starter untrained | Starter trained | Expanded untrained | Expanded trained |\n|---|---|---|---|---|---|')
for i in range(48):
 c=s['cases']['untrained'][i]
 b(f"| {c['id']} | {c['category']} | "+' | '.join(f"{r['cases'][st][i]['score']} / {r['cases'][st][i]['status']}" for r in [s,e] for st in ['untrained','final'])+' |')
b('## Every trained free continuation: direct comparison')
b('These text continuations are sampled from the full vocabulary and are not the four-choice score. They are shown even when the case is unscorable or the continuation is nonsensical. An empty string is explicitly marked.')
b('| ID | Prompt | Starter trained continuation | Expanded trained continuation |\n|---|---|---|---|')
for x,y in zip(s['cases']['final'],e['cases']['final']): b(f"| {x['id']} | `{cell(x['prompt'])}` | `{cell(x['generated_text']) or '[empty output]'}` | `{cell(y['generated_text']) or '[empty output]'}` |")
(ROOT/'docs/learning_evidence.md').write_text(re.sub(r'(?m)(^\|[^\n]*\|)\n\n(?=\|)', r'\1\n', '\n\n'.join(out))+'\n')
print('Wrote README.md and docs/learning_evidence.md from both complete runs.')
